import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { demoWorkspace, emptyWorkspace } from '../../domain/workspace'
import {
  applyReviewedSales,
  guessMapping,
  parseCsv,
  reviewRows,
  type Interpretation,
} from './intake'
import {
  applyBulkImport,
  guessBulkMapping,
  reviewBulkRows,
  type ImportDataset,
} from './bulk-intake'
import { workspaceToImportCsv } from './workspace-csv'

const interpretation: Interpretation = {
  dateFormat: 'iso',
  unit: '',
  currency: 'MXN',
  amountBasis: 'Net sales excluding tax, after discounts and returns',
  rowMeaning: 'transaction',
  duplicatesReviewed: false,
}

const directory = join(process.cwd(), 'demo-csv')
const sourceWorkspace = demoWorkspace('csv-export-source')
const generated = workspaceToImportCsv(sourceWorkspace)

if (process.env.UPDATE_DEMO_CSV === '1')
  for (const [name, contents] of Object.entries(generated))
    writeFileSync(join(directory, name), contents)

const demo = (name: keyof typeof generated) =>
  parseCsv(readFileSync(join(directory, name), 'utf8'))

describe('mock showcase CSV bundle', () => {
  it('is generated byte-for-byte from the existing demo workspace', () => {
    for (const [name, contents] of Object.entries(generated))
      expect(
        readFileSync(join(directory, name), 'utf8'),
        `${name} drifted from demoWorkspace`,
      ).toBe(contents)
  })

  it('imports all four exports in the documented order', () => {
    let workspace = emptyWorkspace('mock-showcase')

    for (const [dataset, name] of [
      ['inventory', '01-inventory-costs.csv'],
      ['suppliers', '03-purchasing-suppliers.csv'],
      ['finance', '04-finance-collections.csv'],
    ] as const satisfies readonly [
      Exclude<ImportDataset, 'sales'>,
      keyof typeof generated,
    ][]) {
      const file = demo(name)
      const mapping = guessBulkMapping(dataset, file.headers)
      const reviewed = reviewBulkRows(
        dataset,
        file,
        mapping,
        interpretation,
        workspace,
      )
      expect(
        reviewed.filter((row) => row.status !== 'usable'),
        `${name} should be showcase-ready`,
      ).toEqual([])
      workspace = applyBulkImport(
        workspace,
        dataset,
        file,
        reviewed,
        interpretation,
        name,
        'csv',
        mapping,
      )

      if (dataset === 'inventory') {
        const sales = demo('02-sales.csv')
        const salesMapping = guessMapping(sales.headers)
        const salesReview = reviewRows(
          sales,
          salesMapping,
          interpretation,
          workspace,
        )
        expect(
          salesReview.filter((row) => row.status !== 'usable'),
          '02-sales.csv should be showcase-ready',
        ).toEqual([])
        workspace = applyReviewedSales(
          workspace,
          sales,
          salesReview,
          interpretation,
          '02-sales.csv',
          'csv',
          salesMapping,
        )
      }
    }

    expect(workspace.products).toHaveLength(sourceWorkspace.products.length)
    expect(workspace.stock).toHaveLength(sourceWorkspace.stock.length)
    expect(workspace.sales).toHaveLength(sourceWorkspace.sales.length)
    expect(workspace.suppliers).toHaveLength(sourceWorkspace.suppliers.length)
    expect(workspace.purchases).toHaveLength(sourceWorkspace.purchases.length)
    expect(workspace.finance).toHaveLength(sourceWorkspace.finance.length)
    expect(workspace.products.map((product) => product.sku)).toContain('ofc 002')
    expect(workspace.sales.map((sale) => sale.amount)).toEqual(
      sourceWorkspace.sales.map((sale) => sale.amount),
    )
    expect(
      workspace.finance.map(({ name, amount, paidAmount }) => ({
        name,
        amount,
        paidAmount,
      })),
    ).toEqual(
      sourceWorkspace.finance.map(({ name, amount, paidAmount }) => ({
        name,
        amount,
        paidAmount,
      })),
    )
  })
})
